name: Triggered Workflow

on:
  repository_dispatch:
    types: [start-workflow]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get Run ID
        run: echo "The workflow run ID is:" ${{ github.run_id }}
        
      - name: Do something
        run: |
          echo "Running tasks in Repo B"
          sleep 120 # Sleep for 120 seconds (2 minutes)

