name: Workflow 1

on:
  repository_dispatch:
    types: [start-workflow-1]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run my build task
        run: |
          echo "Executing the build task for Workflow 1..."
          # Your actual build/test/deployment commands here
          # For example:
          # npm install
          # npm test
          # npm run build
          sleep 30 # Simulate a task taking time
          echo "Workflow 1 completed successfully."
