name: Workflow 1

on:
  repository_dispatch:
    types: [start-workflow-1]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run my build task
        run: |
          echo "Executing the build task for Workflow 1..."
          echo "Workflow in the other repository Started"
          sleep 30 
          echo "Workflow in the other repo completed"
          echo "Workflow 1 completed successfully."
